openapi: 3.0.3
info:
  title: Pinecone
  description: Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
  contact:
    name: Pinecone Support
    url: https://support.pinecone.io
    email: support@pinecone.io
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
  version: 2024-07

servers:
- url: https://api.pinecone.io
  description: Production API endpoints
  x-fern-server-name: Default

x-fern-global-headers:
  - header: X-Pinecone-API-Version
    name: version
    type: literal<"2024-10">

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Api-Key
      x-fern-header:
        name: apiKey
        env: PINECONE_API_KEY

paths: []
